name: CI tests
on:
  pull_request:

  push:
    branches:
      - main

env:
  FORCE_COLOR: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Run linters and other pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.x"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker build -t datalab-cheminventory-plugin .
