name: Build and optionally publish Docker container
on:
  release:
    types:
    - published
  pull_request:
  push:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    docker:
      name: Build and push Docker image
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write

      steps:
        - uses: actions/checkout@v4

        - name : Login to ${{ env.REGISTRY }} Docker registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata from GitHub release
          id: metadata
          uses: docker/metadata-action@v5
          with:
            imges: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push image
          id: push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: ${ github.event_name == 'release' }
            tags: |
              ${{ steps.metadata.outputs.tags }}
              ${{ steps.metadata.outputs.tags_latest }}
            labels: |
              org.opencontainers.image.revision=${{ github.sha }}
              org.opencontainers.image.created=${{ github.event.release.created_at }}
              org.opencontainers.image.version=${{ github.event.release.tag_name }}

        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v2
          if: github.event_name == 'release'
          with:
            subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            subject-digest: ${{ steps.push.outputs.digest }}
            push-to-registry: true
