name: Publish Docker container
on:
  release:
    types:
    - published

jobs:
    docker:
      name: Build and push Docker image
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - run: |
            docker build -t ghcr.io/datalab-industries/datalab-cheminventory-plugin:latest .
            docker tag ghcr.io/datalab-industries/datalab-cheminventory-plugin:latest ghcr.io/datalab-industries/datalab-cheminventory-plugin:${{ github.event.release.tag_name }}
            docker push ghcr.io/datalab-industries/datalab-cheminventory-plugin:latest
            docker push ghcr.io/datalab-industries/datalab-cheminventory-plugin:${{ github.event.release.tag_name }}
